# Generated by Django 4.2.8 on 2023-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("singer", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
